// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModelAdapter(arg1) {
  return window['go']['bridge']['ProxyService']['AddModelAdapter'](arg1);
}

export function ClearRequestLogs() {
  return window['go']['bridge']['ProxyService']['ClearRequestLogs']();
}

export function EnsureCACertificateTrusted() {
  return window['go']['bridge']['ProxyService']['EnsureCACertificateTrusted']();
}

export function EnsureCATrustOnStartup() {
  return window['go']['bridge']['ProxyService']['EnsureCATrustOnStartup']();
}

export function FixIssues(arg1) {
  return window['go']['bridge']['ProxyService']['FixIssues'](arg1);
}

export function GetCACertificate() {
  return window['go']['bridge']['ProxyService']['GetCACertificate']();
}

export function GetCACertificateTrustStatus() {
  return window['go']['bridge']['ProxyService']['GetCACertificateTrustStatus']();
}

export function GetDiagnostics() {
  return window['go']['bridge']['ProxyService']['GetDiagnostics']();
}

export function GetState() {
  return window['go']['bridge']['ProxyService']['GetState']();
}

export function GetTrayState() {
  return window['go']['bridge']['ProxyService']['GetTrayState']();
}

export function ListModelAdapters() {
  return window['go']['bridge']['ProxyService']['ListModelAdapters']();
}

export function ListRequestLogs() {
  return window['go']['bridge']['ProxyService']['ListRequestLogs']();
}

export function LoadUserConfig() {
  return window['go']['bridge']['ProxyService']['LoadUserConfig']();
}

export function RemoveModelAdapter(arg1) {
  return window['go']['bridge']['ProxyService']['RemoveModelAdapter'](arg1);
}

export function RepairCursorBootstrapCacheOnStartup() {
  return window['go']['bridge']['ProxyService']['RepairCursorBootstrapCacheOnStartup']();
}

export function RestoreCursorSettings() {
  return window['go']['bridge']['ProxyService']['RestoreCursorSettings']();
}

export function RestoreProxyOnStartup() {
  return window['go']['bridge']['ProxyService']['RestoreProxyOnStartup']();
}

export function SaveUserConfig(arg1) {
  return window['go']['bridge']['ProxyService']['SaveUserConfig'](arg1);
}

export function SetBaseURL(arg1) {
  return window['go']['bridge']['ProxyService']['SetBaseURL'](arg1);
}

export function StartProxy() {
  return window['go']['bridge']['ProxyService']['StartProxy']();
}

export function StopProxy() {
  return window['go']['bridge']['ProxyService']['StopProxy']();
}

export function TestModelAdapter(arg1) {
  return window['go']['bridge']['ProxyService']['TestModelAdapter'](arg1);
}
