// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {relay} from '../models';
import {certs} from '../models';
import {bridge} from '../models';
import {config} from '../models';

export function AddModelAdapter(arg1:relay.ModelAdapter):Promise<void>;

export function ClearRequestLogs():Promise<void>;

export function EnsureCACertificateTrusted():Promise<certs.TrustStatus>;

export function EnsureCATrustOnStartup():Promise<void>;

export function FixIssues(arg1:bridge.FixOptions):Promise<bridge.FixResult>;

export function GetCACertificate():Promise<string>;

export function GetCACertificateTrustStatus():Promise<certs.TrustStatus>;

export function GetDiagnostics():Promise<bridge.DiagnosticsDTO>;

export function GetState():Promise<bridge.ProxyState>;

export function GetTrayState():Promise<bridge.TrayState>;

export function ListModelAdapters():Promise<Array<relay.ModelAdapter>>;

export function ListRequestLogs():Promise<Array<bridge.RequestLogEntry>>;

export function LoadUserConfig():Promise<config.UserConfig>;

export function RemoveModelAdapter(arg1:string):Promise<void>;

export function RepairCursorBootstrapCacheOnStartup():Promise<void>;

export function RestoreCursorSettings():Promise<bridge.ProxyState>;

export function RestoreProxyOnStartup():Promise<void>;

export function SaveUserConfig(arg1:config.UserConfig):Promise<void>;

export function SetBaseURL(arg1:string):Promise<bridge.ProxyState>;

export function StartProxy():Promise<bridge.ProxyState>;

export function StopProxy():Promise<bridge.ProxyState>;

export function TestModelAdapter(arg1:relay.ModelAdapter):Promise<string>;
